<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <form action="validate.PHP" method="POST">
<h1>Validate FORM</h1>
    <span>Username</span>
    <input type="text" placeholder="Username" name="username"> <br> Password
    <input type="text" placeholder="password" name="password"><br>
    <input type="submit"  value="Login" name="Login">
</body>
</html>